### PR TITLE
Add matlab compiled Kilosort

### PR DESCRIPTION
**Pull request by chyumin**
Added instructions to compile and build a base image with compiled kilosort3
Added matlab scripts used to compile (is there any better place to add it?)
Added Dockerfile to extend matlab-base image to add improvements and fixes to properly run kilosort3

### CODE REVIEW

**Comment by bendichter** [comment]
@chyumin can you merge my suggestions for this PR?

**Comment by bendichter** [comment]
@chyumin you are right, I forgot to submit them. You should be able to see them now

**Comment by chyumin** [comment]
@bendichter Merged
Thank you

**Comment by chyumin** [comment]
Renaming branch caused PR to automatically close. Recreated as PR #25

**Pull request closed without merging**
