### PR TITLE
Ci test gpu

### PR DESCRIPTION
**Pull request by bendichter**

### CODE REVIEW

**Comment by bendichter** [comment]
@chyumin can you please edit this so these tests are skipped by the non-GPU CI workflow?

**Comment by bendichter** [comment]
@alejoe91 it looks like this PR may require setting some secrets

**Comment by chyumin** [comment]
> @chyumin can you please edit this so these tests are skipped by the non-GPU CI workflow?

@bendichter I moved gpu tests into another test file, so non-gpu ci tests workflow won't run gpu tests. See [here](https://github.com/SpikeInterface/spikeinterface-dockerfiles/blob/ddde7a85efff5b75539fc14ff9487aeba8b45ceb/.github/workflows/test_containers_singularity.yml#L35)

**Comment by alejoe91** [comment]
> @alejoe91 it looks like this PR may require setting some secrets

@bendichter @chyumin let's have a call early next week to finish this up :)

**Comment by bendichter** [comment]
@alejoe91 and @chyumin would you be available at 10:30 ET on Monday?

**Comment by alejoe91** [comment]
Works for me :)

**Pull request merged**
