### PR TITLE
add mountainsort5 and bump mountainsort4

### PR DESCRIPTION
**Pull request by magland**

### CODE REVIEW

**Comment by magland** [comment]
I don't have permission to push the docker images - so I guess @alejoe91 you'll need to build and push.

**Comment by alejoe91** [comment]
@magland you should have access to the spikeinterface org! 
image

**Comment by magland** [comment]
Oh yes you are right, I forgot to log in. I pushed the images, so should be good now.

**Comment by alejoe91** [comment]
@magland I built and push v0.1.5 because the one you pushed (0.1.2) didn't have the `__version__`

**Pull request merged**
