### PR TITLE
add mountainsort4 image

### PR DESCRIPTION
**Pull request by magland**
I made a cleaned-up package of ml_ms4alg called [mountainsort4](https://github.com/magland/mountainsort4) which is now on pypi. It's the same algorithm, just simplified packaging and some cleanup of the source code.

This docker image simply pip installs that package.

Here's the spikeforest image, wrapper, and example:
https://github.com/flatironinstitute/spikeforest/blob/main/spikeforest/sorters/mountainsort4/docker/Dockerfile
https://github.com/flatironinstitute/spikeforest/blob/main/spikeforest/sorters/mountainsort4/mountainsort4_wrapper1.py
https://github.com/flatironinstitute/spikeforest/blob/main/devel/sorting/test_mountainsort4.py

### CODE REVIEW

**Comment by magland** [comment]
@alejoe91 @bendichter @samuelgarcia @jsoules

**Comment by bendichter** [comment]
Well that's pretty simple! Why install numpy before mountainsort? Surely numpy as a requirement of mountainsort, right?

**Comment by magland** [comment]
> Well that's pretty simple! Why install numpy before mountainsort? Surely numpy as a requirement of mountainsort, right?

I usually don't put numpy in the list of requirements in setup.py because some people have their own system-wide numpy installed and the pip install numpy can sometimes cause problems. Not sure if this is the recommended strategy.

Nevertheless, another reason to do it (although not super important), is that the layer of `python:3.8 + (pip install numpy)` can be shared across multiple images, and that saves a bit of time.

**Comment by samuelgarcia** [comment]
Hi Jeremy.
Is there a MS4 package on pypi now ?
I was using ml-ms4alg but it was failing on ubuntu 20.4 + py3.8.

**Comment by magland** [comment]
mountainsort4 is on pypi. please give it a try and let me know if that is
also failing.

**Comment by magland** [comment]
I'll merge this unless anyone has objection.

**Pull request merged**
