### PR TITLE
Readd pykilosort test

### PR DESCRIPTION
**Pull request by chyumin**
This PR should be merged only after https://github.com/SpikeInterface/spikeinterface/pull/890

### CODE REVIEW

**Comment by bendichter** [comment]
['Warning! The recording is already filtered, but combinato filter is enabled\n', 'Traceback (most recent call last):\n  File "/tmp/pytest-of-runner/pytest-0/test_combinato0/in_container_sorter_script.py", line 17, in <module>\n    sorting = run_sorter_local(\n  File "/home/runner/.local/lib/python3.8/site-packages/spikeinterface/sorters/runsorter.py", line 161, in run_sorter_local\n    SorterClass.setup_recording(recording, output_folder, verbose=verbose)\n  File "/home/runner/.local/lib/python3.8/site-packages/spikeinterface/sorters/basesorter.py", line 196, in setup_recording\n    cls._setup_recording(recording, output_folder, sorter_params, verbose)\n  File "/home/runner/.local/lib/python3.8/site-packages/spikeinterface/sorters/combinato/combinato.py", line 138, in _setup_recording\n    write_to_h5_dataset_format(recording, dataset_path=\'/data\', segment_index=0,\n  File "/home/runner/.local/lib/python3.8/site-packages/spikeinterface/core/core_tools.py", line 560, in write_to_h5_dataset_format\n    traces = recording.get_traces(segment_index=segment_index,\n  File "/home/runner/.local/lib/python3.8/site-packages/spikeinterface/core/baserecording.py", line 144, in get_traces\n    raise ValueError(\'This recording do not support return_scaled=True (need gain_to_uV and offset_\'\nValueError: This recording do not support return_scaled=True (need gain_to_uV and offset_to_uV properties)\n']

Is it possible to use `return_scaled=False`?

**Comment by chyumin** [comment]
@bendichter @alejoe91 This error is happening after this change:
https://github.com/SpikeInterface/spikeinterface/pull/908/files#diff-91a9c642bdff905864e37e0b04e25b5e11b05e0a33169df99863d18d8ac4d703R140

**Comment by chyumin** [comment]
Converting this PR to draft because pykilosort test is still failing

**Comment by chyumin** [comment]
This [PR](https://github.com/SpikeInterface/spikeinterface/pull/938) should fix pykilosort test error.

**Pull request merged**
