### PR TITLE
Pykilosort

### PR DESCRIPTION
**Pull request by vncntprvst**
Here's a first pass at a pyKilosort container for spikeinterface. It's not fully working yet but I wanted to get some feedback. 
First point, I followed the README instructions and used the `drift_test_stable` from `kushbanga`'s fork. It does look fairly far ahead of the original repo (IBL's fork also has a divergent `prod` branch with recent push). I assume this is fine.
Second, when testing pyKilosort within the container:
``` 
In [1]: from pathlib import Path
   ...: from pykilosort import run, add_default_handler, np1_probe, np2_probe

In [2]: data_path = Path('/data/Allen_Institute_NP1/continuous_1min.bin')
   ...: dir_path = Path('/data/Allen_Institute_NP1/pyKS_output')
   ...: add_default_handler(level='INFO')

In [3]: run(data_path, dir_path=dir_path, probe=np1_probe())
23:24:19.214 [I] utils:277            Loaded data with 385 channels, 1795324 samples
23:24:19.216 [I] utils:557            Starting step drift_correction.
23:24:19.216 [I] datashift2:618       pitch is 20.0 um
Extracting templates: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.88it/s]
---------------------------------------------------------------------------
```
I get this error  

```
IndexError                                Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 run(data_path, dir_path=dir_path, probe=np1_probe())

File /src/pykilosort/pykilosort/main.py:175, in run(dat_path, dir_path, output_dir, probe, stop_after, clear_context, **params)
    173     if "drift_correction" not in ctx.timer.keys():
    174         with ctx.time("drift_correction"):
--> 175             out = datashift2(ctx)
    176         ctx.save(**out)
    177 else:

File /src/pykilosort/pykilosort/datashift2.py:635, in datashift2(ctx)
    632     np.random.seed(params.seed)
    634 # determine prototypical timecourses by clustering of simple threshold crossings.
--> 635 wTEMP, wPCA = extractTemplatesfromSnippets(
    636     data_loader=ir.data_loader, probe=probe, params=params, Nbatch=Nbatch
    637 )
    639 # Extract all the spikes across the recording that are captured by the
    640 # generic templates. Very few real spikes are missed in this way.
    641 spikes = standalone_detector(
    642     wTEMP, wPCA, params.nPCs, yup, xup, Nbatch, ir.data_loader, probe, params
    643 )

File /src/pykilosort/pykilosort/learn.py:69, in extractTemplatesfromSnippets(data_loader, probe, params, Nbatch, nPCs)
     66     amax = cc[imax, np.arange(cc.shape[1])]
     67     for j in range(nPCs):
     68         # weighted average to get new cluster means
---> 69         wTEMP[:, j] = cp.dot(dd[:, imax == j], amax[imax == j].T)
     70     wTEMP = wTEMP / cp.sum(wTEMP ** 2, axis=0) ** 0.5  # unit normalize
     72 # the PCs are just the left singular vectors of the waveforms

File cupy/_core/core.pyx:1508, in cupy._core.core.ndarray.__setitem__()

File cupy/_core/_routines_indexing.pyx:51, in cupy._core._routines_indexing._ndarray_setitem()

File cupy/_core/_routines_indexing.pyx:967, in cupy._core._routines_indexing._scatter_op()

File cupy/_core/_routines_indexing.pyx:433, in cupy._core._routines_indexing._view_getitem()

IndexError: Index 0 is out of bounds for axis 1 with size 0
```
I'll debug this further this week, but if anyone (@oliche ?) has an idea of what's happening here, I'm happy to hear it. 
Thanks!

### CODE REVIEW

**Comment by alejoe91** [comment]
I actually also tried to run it and ended up with the exact same error! It would be great to hear from @oliche and @kushbunga

**Comment by kushbanga** [comment]
This error occurs when the algorithm is searching for generic spike templates to use for detection and is unable to find any isolated spike events. Usually this means the data has been loaded incorrectly into the function (eg. wrong no of channels or wrong dtype)

**Comment by kushbanga** [comment]
The np1_probe assumes the data has 385 channels, is it possible this dataset only has 384?

**Comment by alejoe91** [comment]
> The np1_probe assumes the data has 385 channels, is it possible this dataset only has 384?

@vncntprvst did you use the test dataset from Josh? Then yes, it has 384 channels. Can you try to set it?
Note that in the SI implementation, the num channels are set automatically based on the recording.

**Comment by kushbanga** [comment]
I've added an option that to remove the sync channel If you switch to the repo linked below (haven't tested it though as I don't have any 384 channel recordings)

https://github.com/MouseLand/pykilosort/tree/develop

You can remove the sync channel by swapping `probe=np1_probe()` with `probe=np1_probe(sync_channel=False)`. Unfortunately kilosort doesn't have an inbuilt method of determining the number of channels in a recording so this needs to be manually provided in the probe geometry

**Comment by vncntprvst** [comment]
I see. Thanks guys! I'll try that and let you know how it goes.

**Comment by kushbanga** [comment]
I just ran it on my end without any errors so it should just be an installation issue. I'm happy to take a look if you share the new error message

**Comment by alejoe91** [comment]
@kushbanga can we contact you on slack? Do you have access to the Spike Sorting Group one?

**Comment by kushbanga** [comment]
Btw `dir_path` is the folder used to store temporary data which gets deleted after the run has finished. You can use the argument `output_dir` if you want to save the output in a specific folder, otherwise it sets `output_dir` to `dir_path / 'output'` by default

**Comment by alejoe91** [comment]
@vncntprvst I tried to run it trhough spikeinterface, but I think that the entrypoint is missing a `conda activate pyks2` (in fact if I run the container `pykilosort` is not installed unless I do `conda activate pyks2`

**Comment by alejoe91** [comment]
> @vncntprvst I tried to run it trhough spikeinterface, but I think that the entrypoint is missing a `conda activate pyks2` (in fact if I run the container `pykilosort` is not installed unless I do `conda activate pyks2`

I remember trying to do it with yass and it's quite tricky. I ended up installing all the requirements in `base`...

**Comment by alejoe91** [comment]
closing in favor of this: https://github.com/SpikeInterface/spikeinterface-dockerfiles/pull/37

**Pull request closed without merging**
